### ISSUE TITLE
Build fails because of unsupported  dotnet version

### ISSUE THREAD

**Issue by achilleasNP** [brain-products/BVTools#3]
The dotnet version 3.0 used by the project is no longer supported. Supported versions are 7.0 and 6.0 
[Dotnet core windows install](https://learn.microsoft.com/en-us/dotnet/core/install/windows?tabs=net70)

Is it possible to update to version 6.0 this only requires changes to the files:

global.json
src/FileFormats/src/FileFormats.BrainVisionToBidsConverterCLI/FileFormats.BrainVisionToBidsConverterCLI.csproj

Thanks,
Achilleas

**Comment by kucint** [comment]
Hi @achilleasNP,
Thanks a lot for your comment.
Indeed, dotnet 3.0 is no longer supported.
We already updated projects to dotnet7 internally and additionally introduced some minor improvements.
Changes will be pushed to GitHub soon (within 2 weeks)
best!
tomasz

**Comment by kucint** [comment]
Hi @achilleasNP 
it went quicker as I thought.
The updated version of Converter (net7.0) is now available.
Best!
tomasz

**Comment by achilleasNP** [comment]
Great! That was quick.

Thanks,
Achilleas
